---
# Install iperf2 dependencies
- name: Install iperf
  apt: name=iperf state=present
  become: true

- name: Install pip3
  apt: name=python3-pip state=present
  become: true

- name: Install PyYaml for python
  pip: name=pyyaml
  become: true

