---
# Run iperf cron jobs

#- name: Install iperf
#  inlcude: install_iperf.yml

- name: Create cron directory if not exists
  file: path=/home/{{ user }}/cronjob state=directory 
        owner={{ user }} group={{ user }}

- name: Copy iperf.py to remote workers
  copy: src=iperf.py dest=/home/{{ user }}/cronjob/ 
        owner={{ user }} group={{ user }} mode=744

- name: Copy config file iperf.yml to remote workers
  template: src=iperf.j2 dest=/home/{{ user }}/cronjob/iperf.yml

- name: Start iperf server on each server
  shell: iperf -s -p {{ iperf_port }}
  async: 45
  poll: 0


#- name: Register to iperf.py as an hourly cron job
#  cron: 
#    - name: "iperf"
#    - job: /home/{{ user }}/cronjob/iperf.py
#    - minute: 0

